"""Data models for knowledge work execution."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Literal


# ---------------------------------------------------------------------------
# Question classification
# ---------------------------------------------------------------------------


class QuestionType(str, Enum):
    """What kind of knowledge task is this?"""

    PROOF = "proof"  # prove/disprove, formal reasoning
    RESEARCH = "research"  # factual research, literature survey
    ANALYSIS = "analysis"  # evaluate, compare, analyze tradeoffs
    SYNTHESIS = "synthesis"  # combine sources into new document
    CREATIVE = "creative"  # write content, blog posts, copy
    DECISION = "decision"  # choose between options, recommend
    ESTIMATION = "estimation"  # quantitative estimates, forecasting


# ---------------------------------------------------------------------------
# Execution patterns
# ---------------------------------------------------------------------------


class PatternType(str, Enum):
    """Which execution pattern to use."""

    ADVERSARIAL = "adversarial"  # advocate + skeptic + judge
    EXPLORATION = "exploration"  # parallel explorers + synthesizer
    DEEPENING = "deepening"  # worker + critic iterating
    TOURNAMENT = "tournament"  # option advocates + comparator
    ESTIMATION = "estimation"  # independent estimators + aggregator


# ---------------------------------------------------------------------------
# Effort levels
# ---------------------------------------------------------------------------

EffortLevel = Literal["quick", "standard", "deep", "exhaustive"]

_EFFORT_DEFAULTS: dict[str, dict] = {
    "quick": {"max_rounds": 1, "max_agents": 2, "max_cycles": 1},
    "standard": {"max_rounds": 3, "max_agents": 4, "max_cycles": 3},
    "deep": {"max_rounds": 8, "max_agents": 8, "max_cycles": 6},
    "exhaustive": {"max_rounds": 20, "max_agents": 15, "max_cycles": 15},
}


# ---------------------------------------------------------------------------
# Convergence
# ---------------------------------------------------------------------------


@dataclass
class ConvergenceState:
    """Tracks how close the answer is to being final."""

    confidence: float = 0.0  # 0-1: how confident in the current answer
    stability: float = 0.0  # 0-1: how much did last iteration change things
    agreement: float = 0.0  # 0-1: do independent lines agree
    completeness: float = 0.0  # 0-1: are known gaps filled
    round_number: int = 0
    history: list[dict] = field(default_factory=list)

    @property
    def converged(self) -> bool:
        if self.confidence >= 0.95 and self.stability >= 0.9:
            return True
        if self.diminishing_returns and self.confidence >= 0.7:
            return True
        return False

    @property
    def diminishing_returns(self) -> bool:
        """Last two rounds produced little change."""
        if len(self.history) < 2:
            return False
        recent = self.history[-2:]
        return all(h.get("stability", 0) >= 0.85 for h in recent)

    @property
    def verdict_type(self) -> str:
        if self.confidence >= 0.9:
            return "strong_conclusion"
        if self.confidence >= 0.6:
            return "qualified_conclusion"
        return "open_question"

    def record_round(self) -> None:
        self.history.append(
            {
                "round": self.round_number,
                "confidence": self.confidence,
                "stability": self.stability,
                "agreement": self.agreement,
                "completeness": self.completeness,
            }
        )


# ---------------------------------------------------------------------------
# Agent roles (dynamic, generated per-task)
# ---------------------------------------------------------------------------


@dataclass
class AgentRole:
    """A dynamically-generated agent role for a knowledge task."""

    name: str  # e.g. "content_writer", "skeptic"
    system_prompt: str  # generated by team designer
    model_preference: str = "best"  # "best", "fast", "search", "compute"
    tools: list[str] = field(default_factory=list)  # tool names this agent needs


@dataclass
class TeamDesign:
    """Complete team designed by the orchestrator for a specific task."""

    roles: list[AgentRole]
    pattern: PatternType
    question_type: QuestionType
    rationale: str  # why this team/pattern was chosen


# ---------------------------------------------------------------------------
# Artifacts (the shared workspace)
# ---------------------------------------------------------------------------


@dataclass
class Artifact:
    """A knowledge artifact in the shared workspace."""

    name: str
    content: str = ""
    version: int = 0


@dataclass
class Workspace:
    """Shared artifact space for a knowledge run."""

    artifacts: dict[str, Artifact] = field(default_factory=dict)

    def write(self, name: str, content: str) -> None:
        if name in self.artifacts:
            self.artifacts[name].content = content
            self.artifacts[name].version += 1
        else:
            self.artifacts[name] = Artifact(name=name, content=content, version=1)

    def read(self, name: str) -> str | None:
        art = self.artifacts.get(name)
        return art.content if art else None

    def list_artifacts(self) -> list[str]:
        return list(self.artifacts.keys())

    def snapshot(self, *, max_chars_per_artifact: int = 500) -> str:
        """Return a text summary of all artifacts for context injection.

        Use max_chars_per_artifact=0 for unlimited (full content).
        """
        parts = []
        for name, art in self.artifacts.items():
            if not art.content:
                preview = "(empty)"
            elif max_chars_per_artifact and len(art.content) > max_chars_per_artifact:
                preview = (
                    art.content[:max_chars_per_artifact]
                    + f"\n... ({len(art.content)} chars total)"
                )
            else:
                preview = art.content
            parts.append(f"## {name} (v{art.version})\n{preview}")
        return "\n\n".join(parts) if parts else "(no artifacts yet)"


# ---------------------------------------------------------------------------
# Run configuration and results
# ---------------------------------------------------------------------------


@dataclass
class KnowledgeGoal:
    """User's input to a knowledge run."""

    goal: str
    effort: EffortLevel = "standard"
    domain_hints: list[str] = field(default_factory=list)
    constraints: list[str] = field(default_factory=list)
    output_format: str | None = (
        None  # "formal_proof", "blog_post", "executive_briefing", etc.
    )
    reference_files: list[str] = field(
        default_factory=list
    )  # paths to files agents should read


@dataclass
class KnowledgeResult:
    """Final output of a knowledge run."""

    answer: str  # the main answer/document
    verdict_type: str = (
        ""  # "strong_conclusion" | "qualified_conclusion" | "open_question"
    )
    confidence: float = 0.0
    reasoning_trace: str = ""  # how we got here
    open_questions: str = ""  # what we couldn't resolve
    rounds_used: int = 0
    total_cost_usd: float = 0.0
    workspace: Workspace | None = None  # full artifact space for inspection
